[package]
name = "packet28-search-core"
version.workspace = true
publish.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[features]
default = []
shared-repository-scan = []

[dependencies]
anyhow.workspace = true
blake3.workspace = true
fs2 = "0.4"
packet28-binary-codec.workspace = true
ignore.workspace = true
memmap2.workspace = true
regex.workspace = true
regex-syntax.workspace = true
serde.workspace = true
serde_json.workspace = true
packet28-reducer-core.workspace = true

[dev-dependencies]
criterion.workspace = true
syn = { version = "2.0.116", features = ["full", "visit"] }
tempfile.workspace = true

[[bench]]
name = "query_attestation"
harness = false
