use super::*;

pub use suite_packet_core::kernel::{
    BudgetUsage, ExecutionBudget, GovernanceAudit, KernelAudit, KernelFailure, KernelPacket,
    KernelRequest, KernelResponse, KernelSequenceRequest, KernelSequenceResponse,
    KernelStepReactiveConfig, KernelStepRequest, KernelStepResponse, ReactiveReplanMode,
    ReactiveSequenceConfig, ReducerExecutionAudit, ReducerResult,
};

#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq, Eq)]
pub struct CacheRuntimeMetrics {
    pub mutation_lock_operations: u64,
    pub mutation_lock_nanos: u64,
    pub persistence: Option<CachePersistenceMetrics>,
    pub persistence_error: Option<String>,
}

fn autogenerated_sequence_step_id(target: &str, index: usize) -> String {
    format!("{}-{index}", target.replace('.', "-"))
}

pub fn normalize_sequence_request(
    mut req: KernelSequenceRequest,
) -> Result<KernelSequenceRequest, KernelError> {
    let mut ids = BTreeSet::new();
    for (index, step) in req.steps.iter_mut().enumerate() {
        if step.target.trim().is_empty() {
            return Err(KernelError::InvalidRequest {
                detail: format!("sequence step {index} target cannot be empty"),
            });
        }

        let trimmed_id = step.id.trim();
        step.id = if trimmed_id.is_empty() {
            autogenerated_sequence_step_id(&step.target, index)
        } else {
            trimmed_id.to_string()
        };

        if !ids.insert(step.id.clone()) {
            return Err(KernelError::InvalidRequest {
                detail: format!("sequence step id '{}' must be unique", step.id),
            });
        }
    }

    for step in &req.steps {
        for dep in &step.depends_on {
            if dep.trim().is_empty() {
                return Err(KernelError::InvalidRequest {
                    detail: format!("sequence step '{}' has an empty dependency id", step.id),
                });
            }
            if dep == &step.id {
                return Err(KernelError::InvalidRequest {
                    detail: format!("sequence step '{}' cannot depend on itself", step.id),
                });
            }
            if !ids.contains(dep) {
                return Err(KernelError::InvalidRequest {
                    detail: format!(
                        "sequence step '{}' depends on unknown step '{}'",
                        step.id, dep
                    ),
                });
            }
        }
    }

    Ok(req)
}

pub trait SequenceObserver {
    /// Returns whether sequence execution should stop at the next cooperative
    /// step boundary.
    ///
    /// Reducers are synchronous, so cancellation does not interrupt a reducer
    /// that is already running. The kernel checks this hook before scheduling a
    /// step and again after observer callbacks.
    fn should_cancel(&self) -> bool {
        false
    }

    fn on_step_started(&mut self, _position: usize, _step: &KernelStepRequest) {}

    fn on_step_completed(
        &mut self,
        _position: usize,
        _step: &KernelStepRequest,
        _response: &KernelResponse,
    ) {
    }

    fn on_step_failed(
        &mut self,
        _position: usize,
        _step: &KernelStepRequest,
        _failure: &KernelFailure,
    ) {
    }

    fn on_replan_applied(
        &mut self,
        _after_step: Option<&str>,
        _event_count: usize,
        _applied_mutations: &Value,
    ) {
    }
}

#[derive(Default)]
pub struct NoopSequenceObserver;

impl SequenceObserver for NoopSequenceObserver {}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum BudgetStage {
    Input,
    Total,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum BudgetMetric {
    Tokens,
    Bytes,
    RuntimeMs,
}

#[derive(Debug, Error)]
pub enum KernelError {
    #[error("kernel target cannot be empty")]
    EmptyTarget,

    #[error("unknown kernel target '{target}'")]
    UnknownTarget {
        target: String,
        registered: Vec<String>,
    },

    #[error("invalid request: {detail}")]
    InvalidRequest { detail: String },

    #[error("budget exceeded for {metric:?} at {stage:?}: used {used} > cap {cap}")]
    BudgetExceeded {
        target: String,
        stage: BudgetStage,
        metric: BudgetMetric,
        used: u64,
        cap: u64,
    },

    #[error("failed to read packet file '{path}': {detail}")]
    PacketRead { path: String, detail: String },

    #[error("failed to parse packet JSON from '{path}': {detail}")]
    PacketParse { path: String, detail: String },

    #[error("reducer '{target}' failed: {detail}")]
    ReducerFailed { target: String, detail: String },

    #[error("scheduler error: {detail}")]
    SchedulerFailed { detail: String },

    #[error("cache lock failed: {detail}")]
    CacheLock { detail: String },

    #[error("cache persistence failed: {detail}")]
    CachePersistence { detail: String },

    #[error("policy violation for target '{target}': {detail}")]
    PolicyViolation { target: String, detail: String },

    #[error("kernel sequence cancelled (task_id={task_id:?})")]
    SequenceCancelled { task_id: Option<String> },
}

impl KernelError {
    pub fn structured(&self) -> KernelFailure {
        match self {
            KernelError::EmptyTarget => KernelFailure {
                code: "empty_target".to_string(),
                message: self.to_string(),
                target: None,
            },
            KernelError::UnknownTarget { target, .. } => KernelFailure {
                code: "unknown_target".to_string(),
                message: self.to_string(),
                target: Some(target.clone()),
            },
            KernelError::InvalidRequest { .. } => KernelFailure {
                code: "invalid_request".to_string(),
                message: self.to_string(),
                target: None,
            },
            KernelError::BudgetExceeded { target, .. } => KernelFailure {
                code: "budget_exceeded".to_string(),
                message: self.to_string(),
                target: Some(target.clone()),
            },
            KernelError::PacketRead { .. } => KernelFailure {
                code: "packet_read_failed".to_string(),
                message: self.to_string(),
                target: None,
            },
            KernelError::PacketParse { .. } => KernelFailure {
                code: "packet_parse_failed".to_string(),
                message: self.to_string(),
                target: None,
            },
            KernelError::ReducerFailed { target, .. } => KernelFailure {
                code: "reducer_failed".to_string(),
                message: self.to_string(),
                target: Some(target.clone()),
            },
            KernelError::SchedulerFailed { .. } => KernelFailure {
                code: "scheduler_failed".to_string(),
                message: self.to_string(),
                target: None,
            },
            KernelError::CacheLock { .. } => KernelFailure {
                code: "cache_lock_failed".to_string(),
                message: self.to_string(),
                target: None,
            },
            KernelError::CachePersistence { .. } => KernelFailure {
                code: "cache_persistence_failed".to_string(),
                message: self.to_string(),
                target: None,
            },
            KernelError::PolicyViolation { target, .. } => KernelFailure {
                code: "policy_violation".to_string(),
                message: self.to_string(),
                target: Some(target.clone()),
            },
            KernelError::SequenceCancelled { .. } => KernelFailure {
                code: "sequence_cancelled".to_string(),
                message: self.to_string(),
                target: None,
            },
        }
    }
}

#[derive(Debug, Clone)]
pub(crate) struct PolicyGuard {
    pub(crate) config: guardy_core::ContextConfig,
    pub(crate) config_path: String,
    pub(crate) policy_hash: String,
}
