#![recursion_limit = "256"]

pub mod agent_surface;
pub mod broker_client;
pub mod ccusage;
mod cli_defs;
mod cli_runtime;
pub mod cmd_agent_prompt;
pub mod cmd_build;
pub mod cmd_common;
pub mod cmd_common_machine;
mod cmd_common_machine_support;
pub mod cmd_common_runtime;
pub mod cmd_compact;
pub mod cmd_context;
pub mod cmd_context_kernel;
pub mod cmd_context_recall;
pub mod cmd_context_state;
pub mod cmd_context_store;
pub mod cmd_cover;
pub mod cmd_daemon;
pub mod cmd_daemon_client;
pub mod cmd_daemon_commands;
pub mod cmd_dashboard;
pub mod cmd_diff;
pub mod cmd_discover;
pub mod cmd_doctor;
pub mod cmd_feedback;
pub mod cmd_graph;
pub mod cmd_guard;
pub mod cmd_hook;
pub mod cmd_impact;
pub mod cmd_init;
pub mod cmd_learn;
pub mod cmd_macos_swap;
pub mod cmd_map;
pub mod cmd_map_query;
pub mod cmd_map_repo;
pub mod cmd_mcp;
pub mod cmd_memory;
pub mod cmd_packet;
pub mod cmd_proxy;
pub mod cmd_run;
pub mod cmd_setup;
pub mod cmd_shard;
pub mod cmd_shell;
pub mod cmd_stack;
pub mod cmd_transcript;
pub mod cmd_verify;
pub mod cmd_wakeup;
pub mod economics;
mod memory_store;
pub mod packet28_agent;
pub mod route_registry;
mod runtime_integrations;
mod savings_analytics;
pub mod task_runtime;
pub(crate) mod toml_filters;

pub use cli_defs::*;
pub use cli_runtime::*;
