[package]
name = "packet28-search-cli"
version.workspace = true
publish.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[[bin]]
name = "p28"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
packet28-daemon-client.workspace = true
packet28-daemon-protocol.workspace = true
packet28-reducer-core.workspace = true
packet28-search-core.workspace = true
serde_json.workspace = true

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true
tempfile.workspace = true
