[package]
name = "covy-core"
version.workspace = true
publish.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
suite-packet-core.workspace = true
suite-foundation-core.workspace = true
diffy-core.workspace = true
testy-core.workspace = true

[dev-dependencies]
roaring.workspace = true
